packageExtensions:
  pug-loader@*:
    dependencies:
      pug: "*"
  "@wizishop/ng-wizi-bulma@*":
    dependencies:
      "@angular/cdk": "^15.0.0"
      rxjs: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-4.2.2.cjs
